version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
            source $HOME/.poetry/env
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest --test-runner playwright tests/test_poetry.py
    working_directory: ~/repo

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              only: main
